var admin=require("firebase-admin"),serviceAccount=require("./key.json"),cors=require("cors");admin.initializeApp({credential:admin.credential.cert(serviceAccount),databaseURL:"https://maverick-ae0b5-default-rtdb.firebaseio.com"});var express=require("express"),app=express();app.use(cors());
var http=require("http").createServer(app),socket=require("socket.io")(http,{cors:{origin:["https://maverick-ae0b5.web.app/Market.html","https://maverick-ae0b5.web.app","https://maverick-ae0b5.web.app/index.html","https://maverick-admin-2k21.web.app/index.html","https://maverick-admin-2k21.web.app"],methods:["GET","POST"]}}),currentStockNumbers,currentStockPrice,current_rec,companyNamesfromBase,defaultDatabase=admin.database();
socket.on("connection",function(a){properLog("SocketConnection","User Connected");a.on("transaction_request",handleTransaction);a.on("change_price_request",changePriceRequest);a.on("change_number_request",changeNumberRequest);a.on("add_participant_request",addParticipantRequest);a.on("add_admin_request",addAdmin);a.on("check_uid",isAuthorizedToAccessMarket);a.on("change_balance_request",changeBalanceRequest);a.on("inc_dec_request",Inc_Dec_Request)});
function isAuthorizedToAccessMarket(a){a=a.PHONE.toString();admin.auth().getUserByPhoneNumber(a).then(function(b){socket.emit("security_check_result",{ADMIN:b.customClaims.admin})})["catch"](function(b){console.log("Error fetching user data:",b)})}function addAdmin(a){var b=a.UID;"HareKrishna01#"===a.PASSWORD&&admin.auth().setCustomUserClaims(b,{admin:!0}).then(function(){properLog("ADMIN","New Admin:"+b+":ADDED")})}
function addParticipantRequest(a){var b=a.TEL_NUMBER;a=a.SCHOOL;var c="",d="",e="";properLog("ADMIN","Team "+a+" is added with "+b);for(var f=0;f<companyNamesfromBase.length-1;f++)c+="0,",d+="0,",e+="0,";c+="0";d+="0";e+="0";defaultDatabase.ref("Participants/+91"+b).set({currentAmount:"10000",currentStocks:c,currentAccounts:d,currentProfits:e,SCHOOL:a})}
function Inc_Dec_Request(a){var b=a.COMPANY,c=parseFloat(currentStockPrice[b])+parseFloat(a.PRICE);properLog("ADMIN","STOCK PRICE OF COMPANY:"+b+" CHANGED TO "+c);a=parseFloat(currentStockPrice[a.COMPANY])-parseFloat(c);currentStockPrice[b]=c.toFixed(2);0<a?current_rec[b]="down":0>a&&(current_rec[b]="up");defaultDatabase.ref("Market/stocksPrice").set(currentStockPrice.toString());defaultDatabase.ref("Market/rec").set(current_rec.toString())}
function changeBalanceRequest(a){var b=a.PHONE;a=a.BALANCE;properLog("ADMIN","AMOUNT OF "+b+" CHANGED TO "+a);defaultDatabase.ref("Participants/"+b.toString()+"/currentAmount").set(a.toString())}
function changePriceRequest(a){var b=a.COMPANY,c=a.PRICE;properLog("ADMIN","STOCK PRICE OF COMPANY:"+b+" CHANGED TO "+c);a=parseFloat(currentStockPrice[a.COMPANY])-parseFloat(c);currentStockPrice[b]=parseFloat(c).toFixed(2);0<a?current_rec[b]="down":0>a&&(current_rec[b]="up");defaultDatabase.ref("Market/stocksPrice").set(currentStockPrice.toString());defaultDatabase.ref("Market/rec").set(current_rec.toString())}
function changeNumberRequest(a){var b=a.COMPANY;a=a.NUMBER;currentStockNumbers[b]=a.toString();properLog("ADMIN","STOCK NUMBER OF COMPANY:"+b+" CHANGED TO "+a);defaultDatabase.ref("Market/stocksLeft").set(currentStockNumbers.toString())}
function handleTransaction(a){if(null===a.UID||void 0===a.UID)properLog("USER","UNAUTHORIZED TRANSACTION BLOCKED");else if("BUY"===a.TYPE)performBuyTransaction(a,socket);else if("SELL"===a.TYPE){var b=parseFloat(currentStockPrice[a.COMPANY])*parseInt(a.NUMBER);var c=currentStockPrice[a.COMPANY];var d=fluctuatePrice(parseFloat(currentStockPrice[a.COMPANY]),"SELL",parseInt(a.NUMBER),parseInt(currentStockNumbers[a.COMPANY]));currentStockPrice[a.COMPANY]=d.PRICE.toFixed(2);currentStockNumbers[a.COMPANY]=
parseInt(d.NUMBER).toString();current_rec[a.COMPANY]="down";d=parseFloat(a.BALANCE);defaultDatabase.ref("Market/stocksPrice").set(currentStockPrice.toString());defaultDatabase.ref("Market/stocksLeft").set(currentStockNumbers.toString());defaultDatabase.ref("Market/rec").set(current_rec.toString());b=(d+(b-.025*b)).toFixed(2);c={STATUS:"SUCCESSFUL",STOCKS_SOLD:a.NUMBER,BALANCE_LEFT:b,COMPANY_ID:a.COMPANY,CPS:c};socket.sockets.emit(a.UID+"sell_status",c);c.COMPANY_ID=companyNamesfromBase[parseInt(c.COMPANY_ID)];
properLog("USER","STOCKS SOLD BY "+a.TEAM+JSON.stringify(c))}}
function performBuyTransaction(a,b){var c=parseInt(a.COMPANY),d=parseInt(a.NUMBER),e=parseFloat(a.AMOUNT),f=a.TEAM,l=currentStockPrice[c],g=parseFloat(currentStockPrice[c])*d,h=a.UID,k=parseFloat(a.BALANCE);parseInt(currentStockNumbers[c])<d?(properLog("USER",'INSUFFICENT STOCKS: THIS HAPPENS WHEN THE STOCK IS CHANGING VERY FAST. DON"T WORRY!'),b.sockets.emit(h+"buy_status",{STATUS:"FAILED",ERROR:"INSUFFCIENT STOCKS IN THE MARKET"})):0!==g-e?g>k&&(b.sockets.emit(h+"buy_status",{STATUS:"FAILED",ERROR:"INSUFFCIENT BALANCE IN YOUR ACCOUNT"}),
properLog("USER",'INSUFFICENT STOCKS: THIS HAPPENS WHEN THE STOCK IS CHANGING VERY FAST. DON"T WORRY!')):(e=fluctuatePrice(parseFloat(currentStockPrice[c]),"BUY",d,parseInt(currentStockNumbers[c])),currentStockPrice[c]=e.PRICE.toFixed(2),currentStockNumbers[c]=parseInt(e.NUMBER).toString(),current_rec[c]="up",defaultDatabase.ref("Market/stocksPrice").set(currentStockPrice.toString()),defaultDatabase.ref("Market/stocksLeft").set(currentStockNumbers.toString()),defaultDatabase.ref("Market/rec").set(current_rec.toString()),
c={STATUS:"SUCCESSFUL",STOCKS_BOUGHT:d,BALANCE_LEFT:(k-(g+.02*g)).toFixed(2),COMPANY_ID:c,CPS:l},b.sockets.emit(h+"buy_status",c),c.COMPANY_ID=companyNamesfromBase[parseInt(c.COMPANY_ID)],properLog("USER","STOCKS BOUGHT BY "+f+JSON.stringify(c)))}http.listen(process.env.PORT||5E3,function(){console.log("listening")});var stocksPrice=defaultDatabase.ref("Market/stocksPrice");stocksPrice.on("value",function(a){currentStockPrice=a.val().split(",")});var stocksNumber=defaultDatabase.ref("Market/stocksLeft");
stocksNumber.on("value",function(a){currentStockNumbers=a.val().split(",")});var companyName=defaultDatabase.ref("Market/Companies");companyName.on("value",function(a){companyNamesfromBase=a.val().split(",")});var recStatus=defaultDatabase.ref("Market/rec");recStatus.on("value",function(a){current_rec=a.val().split(",")});function properLog(a,b){console.log(a+":"+b)}
function fluctuatePrice(a,b,c,d){var e;if("BUY"===b){for(b=0;b<c;b++)300<d&&400>=d?e=.12:200<d&300>=d?e=.13:100<d&&200>=d?e=.15:0<d&&100>=d&&(e=.2),a+=e,--d;return{PRICE:a,NUMBER:d}}if("SELL"===b){b=d;if(5===a)return{PRICE:a,NUMBER:d+c};for(var f=0;f<c;f++)if(300<b&&400>=b?e=.2:200<b&300>=b?e=.15:100<b&&200>=b?e=.13:0<=b&&100>=b&&(e=.12),a-=e,b+=1,5>a){a=5;break}return{PRICE:a,NUMBER:d+c}}};